module.exports = {
  LOGIN_FORM_DATA: 'LOGIN_FORM_DATA',
  GET_DB_NAMES: 'GET_DB_NAMES',
  GET_DB_NAMES_REPLY: 'GET_DB_NAMES_REPLY',
  GET_TABLE_NAMES: 'GET_TABLE_NAMES',
  GET_TABLE_NAMES_REPLY: 'GET_TABLE_NAMES_REPLY',
  GET_TABLE_CONTENTS: 'GET_TABLE_CONTENTS',
  GET_TABLE_CONTENTS_REPLY: 'GET_TABLE_CONTENTS_REPLY',
  CLOSE_SERVER: 'CLOSE_SERVER',
};
